source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Powerline' do
project './powerline.xcodeproj'
  pod 'Fabric'
  pod 'Mixpanel'
  pod 'Crashlytics'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end
