source 'https://github.com/CocoaPods/Specs.git'
# use_frameworks!
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Powerline' do
project './powerline.xcodeproj'
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-fishhook', :path => '../node_modules/react-native/Libraries/fishhook'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'


  pod 'Fabric'
  pod 'Mixpanel'
  pod 'Crashlytics'
  pod 'RSKImageCropper'
  pod 'QBImagePickerController'
  pod 'Stripe', '~> 14.0.0'

  pod 'RNFS', :path => '../node_modules/react-native-fs'
  use_native_modules!
  # pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  # pod 'React', path: '../node_modules/react-native', subspecs: [
  #   'Core',
  #   'jschelpers',
  #   'cxxreact',
  #   'CxxBridge',
  #   'DevSupport',
  #   'RCTText',
  #   'RCTImage',
  #   'RCTNetwork',
  #   'RCTActionSheet',
  #   'RCTAnimation',
  #   'RCTWebSocket',
  # ]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'yoga'
          target.build_configurations.each do |config|
              config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
              config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'NO'
          end
      end
      if target.name == "React"
        target.remove_from_project
      end
  end
end
